services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
